package br.com.plastecno.service.constante;

public enum ParametroConfiguracaoSistema {
	CNAE, DIAS_INATIVIDADE_CLIENTE, DIRETORIO_XML_NFE, NOME_SERVIDOR_SMTP, PERCENTUAL_COFINS, PERCENTUAL_PIS, PORTA_SERVIDOR_SMTP, REGIME_TRIBUTACAO, SSL_HABILITADO_PARA_SMTP
}
