package br.com.plastecno.service.constante;

public enum ParametroConfiguracaoSistema {
	DIAS_INATIVIDADE_CLIENTE, NOME_SERVIDOR_SMTP, PERCENTUAL_COFINS, PERCENTUAL_PIS, PORTA_SERVIDOR_SMTP, REGIME_TRIBUTACAO, SSL_HABILITADO_PARA_SMTP
}
