package br.com.plastecno.service.constante;

public enum SituacaoPedido {
	DIGITACAO ("PEDIDO EM DIGITAÇÃO") ,
	ORCAMENTO ("PEDIDO EM ORÇAMENTO"),
	ENVIADO ("PEDIDO ENVIADO"),
	CANCELADO ("PEDIDO CANCELADO"),
	COMPRA_AGUARDANDO_RECEBIMENTO("COMPRA AGUARDANDO RECEBIMENTO"),
	COMPRA_RECEBIDA("COMPRA RECEBIDA"),
	REVENDA_AGUARDANDO_EMPACOTAMENTO("REVENDA AGUARDANDO EMPACOTAMENTO"),
	REVENDA_AGUARDANDO_ENCOMENDA("REVENDA AGUARDANDO ENCOMENDA"),
	EMPACOTADO("PEDIDO EMPACOTADO"),
	COMPRA_ENCOMENDADA("ENCOMENDA"),
	REVENDA_ENCOMENDADA("REVENDA ENCOMENDADA"),
	REVENDA_PARCIALMENTE_RESERVADA("REVENDA PARCIALMENTE RESERVADA");
	
	private String descricao;
	
	private SituacaoPedido(String descricao){
		this.descricao = descricao;
	}
	
	public String getDescricao(){
		return this.descricao;
	}
}
