alter table vendas.tb_representada add telefone varchar(15) default null;
UPDATE vendas.tb_representada SET telefone = '1130219600' where nome_fantasia = 'PLASTECNO MATRIZ';

insert into vendas.tb_configuracao_sistema (parametro, valor) values ('PERCENTUAL_COFINS', '3');
insert into vendas.tb_configuracao_sistema (parametro, valor) values ('PERCENTUAL_PIS', '0.65');
insert into vendas.tb_configuracao_sistema (parametro, valor) values ('REGIME_TRIBUTACAO', '3');


create table vendas.tb_cfop (
	codigo integer not null,
	descricao varchar(400) not null 
);
ALTER TABLE vendas.tb_cfop ADD PRIMARY KEY (codigo);

insert into vendas.tb_cfop (codigo, descricao) values (1101, 'Compra p/ industrialização ou produção rural');
insert into vendas.tb_cfop (codigo, descricao) values (1102, 'Compra p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (1111, 'Compra p/ industrialização de mercadoria recebida anteriormente em consignação industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1113, 'Compra p/ comercialização, de mercadoria recebida anteriormente em consignação mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (1116, 'Compra p/ industrialização ou produção rural originada de encomenda p/ recebimento futuro');
insert into vendas.tb_cfop (codigo, descricao) values (1117, 'Compra p/ comercialização originada de encomenda p/ recebimento futuro');
insert into vendas.tb_cfop (codigo, descricao) values (1118, 'Compra de mercadoria p/ comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem.');
insert into vendas.tb_cfop (codigo, descricao) values (1120, 'Compra p/ industrialização, em venda à ordem, já recebida do vendedor remetente');
insert into vendas.tb_cfop (codigo, descricao) values (1121, 'Compra p/ comercialização, em venda à ordem, já recebida do vendedor remetente');
insert into vendas.tb_cfop (codigo, descricao) values (1122, 'Compra p/ industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (1124, 'Industrialização efetuada por outra empresa');
insert into vendas.tb_cfop (codigo, descricao) values (1125, 'Industrialização efetuada por outra empresa quando a mercadoria remetida p/ utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria');
insert into vendas.tb_cfop (codigo, descricao) values (1126, 'Compra p/ utilização na prestação de serviço sujeita ao ICMS');
insert into vendas.tb_cfop (codigo, descricao) values (1128, 'Compra p/ utilização na prestação de serviço sujeita ao ISSQN');
insert into vendas.tb_cfop (codigo, descricao) values (1151, 'Transferência p/ industrialização ou produção rural');
insert into vendas.tb_cfop (codigo, descricao) values (1152, 'Transferência p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (1153, 'Transferência de energia elétrica p/ distribuição');
insert into vendas.tb_cfop (codigo, descricao) values (1154, 'Transferência p/ utilização na prestação de serviço');
insert into vendas.tb_cfop (codigo, descricao) values (1201, 'Devolução de venda de produção do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (1202, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (1203, 'Devolução de venda de produção do estabelecimento, destinada à ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (1204, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (1205, 'Anulação de valor relativo à prestação de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (1206, 'Anulação de valor relativo à prestação de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (1207, 'Anulação de valor relativo à venda de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (1208, 'Devolução de produção do estabelecimento, remetida em transferência');
insert into vendas.tb_cfop (codigo, descricao) values (1209, 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência');
insert into vendas.tb_cfop (codigo, descricao) values (1212, 'Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (1251, 'Compra de energia elétrica p/ distribuição ou comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (1252, 'Compra de energia elétrica por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1253, 'Compra de energia elétrica por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (1254, 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (1255, 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (1256, 'Compra de energia elétrica por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (1257, 'Compra de energia elétrica p/ consumo por demanda contratada');
insert into vendas.tb_cfop (codigo, descricao) values (1301, 'Aquisição de serviço de comunicação p/ execução de serviço da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (1302, 'Aquisição de serviço de comunicação por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1303, 'Aquisição de serviço de comunicação por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (1304, 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (1305, 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (1306, 'Aquisição de serviço de comunicação por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (1351, 'Aquisição de serviço de transporte p/ execução de serviço da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (1352, 'Aquisição de serviço de transporte por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1353, 'Aquisição de serviço de transporte por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (1354, 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (1355, 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (1356, 'Aquisição de serviço de transporte por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (1360, 'Aquisição de serviço de transporte por contribuinte-substituto em relação ao serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (1401, 'Compra p/ industrialização ou produção rural de mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1403, 'Compra p/ comercialização em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1406, 'Compra de bem p/ o ativo imobilizado cuja mercadoria está sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1407, 'Compra de mercadoria p/ uso ou consumo cuja mercadoria está sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1408, 'Transferência p/ industrialização ou produção rural de mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1409, 'Transferência p/ comercialização em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1410, 'Devolução de venda de mercadoria, de produção do estabelecimento, sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1411, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1414, 'Retorno de mercadoria de produção do estabelecimento, remetida p/ venda fora do estabelecimento, sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1415, 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida p/ venda fora do estabelecimento em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (1451, 'Retorno de animal do estabelecimento produtor');
insert into vendas.tb_cfop (codigo, descricao) values (1452, 'Retorno de insumo não utilizado na produção');
insert into vendas.tb_cfop (codigo, descricao) values (1501, 'Entrada de mercadoria recebida com fim específico de exportação');
insert into vendas.tb_cfop (codigo, descricao) values (1503, 'Entrada decorrente de devolução de produto, de fabricação do estabelecimento, remetido com fim específico de exportação');
insert into vendas.tb_cfop (codigo, descricao) values (1504, 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (1505, 'Entrada decorrente de devolução simbólica de mercadoria remetida p/ formação de lote de exportação, de produto industrializado ou produzido pelo próprio estabelecimento.');
insert into vendas.tb_cfop (codigo, descricao) values (1506, 'Entrada decorrente de devolução simbólica de mercadoria, adquirida ou recebida de terceiros, remetida p/ formação de lote de exportação.');
insert into vendas.tb_cfop (codigo, descricao) values (1551, 'Compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (1552, 'Transferência de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (1553, 'Devolução de venda de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (1554, 'Retorno de bem do ativo imobilizado remetido p/ uso fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (1555, 'Entrada de bem do ativo imobilizado de terceiro, remetido p/ uso no estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (1556, 'Compra de material p/ uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (1557, 'Transferência de material p/ uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (1601, 'Recebimento, por transferência, de crédito de ICMS');
insert into vendas.tb_cfop (codigo, descricao) values (1602, 'Recebimento, por transferência, de saldo credor do ICMS, de outro estabelecimento da mesma empresa, p/ compensação de saldo devedor do imposto. ');
insert into vendas.tb_cfop (codigo, descricao) values (1603, 'Ressarcimento de ICMS retido por substituição tributária');
insert into vendas.tb_cfop (codigo, descricao) values (1604, 'Lançamento do crédito relativo à compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (1605, 'Recebimento, por transferência, de saldo devedor do ICMS de outro estabelecimento da mesma empresa');
insert into vendas.tb_cfop (codigo, descricao) values (1651, 'Compra de combustível ou lubrificante p/ industrialização subseqüente');
insert into vendas.tb_cfop (codigo, descricao) values (1652, 'Compra de combustível ou lubrificante p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (1653, 'Compra de combustível ou lubrificante por consumidor ou usuário final');
insert into vendas.tb_cfop (codigo, descricao) values (1658, 'Transferência de combustível ou lubrificante p/ industrialização');
insert into vendas.tb_cfop (codigo, descricao) values (1659, 'Transferência de combustível ou lubrificante p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (1660, 'Devolução de venda de combustível ou lubrificante destinados à industrialização subseqüente');
insert into vendas.tb_cfop (codigo, descricao) values (1661, 'Devolução de venda de combustível ou lubrificante destinados à comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (1662, 'Devolução de venda de combustível ou lubrificante destinados a consumidor ou usuário final');
insert into vendas.tb_cfop (codigo, descricao) values (1663, 'Entrada de combustível ou lubrificante p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (1664, 'Retorno de combustível ou lubrificante remetidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (1901, 'Entrada p/ industrialização por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (1902, 'Retorno de mercadoria remetida p/ industrialização por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (1903, 'Entrada de mercadoria remetida p/ industrialização e não aplicada no referido processo');
insert into vendas.tb_cfop (codigo, descricao) values (1904, 'Retorno de remessa p/ venda fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (1905, 'Entrada de mercadoria recebida p/ depósito em depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (1906, 'Retorno de mercadoria remetida p/ depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (1907, 'Retorno simbólico de mercadoria remetida p/ depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (1908, 'Entrada de bem por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (1909, 'Retorno de bem remetido por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (1910, 'Entrada de bonificação, doação ou brinde');
insert into vendas.tb_cfop (codigo, descricao) values (1911, 'Entrada de amostra grátis');
insert into vendas.tb_cfop (codigo, descricao) values (1912, 'Entrada de mercadoria ou bem recebido p/ demonstração');
insert into vendas.tb_cfop (codigo, descricao) values (1913, 'Retorno de mercadoria ou bem remetido p/ demonstração');
insert into vendas.tb_cfop (codigo, descricao) values (1914, 'Retorno de mercadoria ou bem remetido p/ exposição ou feira');
insert into vendas.tb_cfop (codigo, descricao) values (1915, 'Entrada de mercadoria ou bem recebido p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (1916, 'Retorno de mercadoria ou bem remetido p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (1917, 'Entrada de mercadoria recebida em consignação mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1918, 'Devolução de mercadoria remetida em consignação mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1919, 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (1920, 'Entrada de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (1921, 'Retorno de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (1922, 'Lançamento efetuado a título de simples faturamento decorrente de compra p/ recebimento futuro');
insert into vendas.tb_cfop (codigo, descricao) values (1923, 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem');
insert into vendas.tb_cfop (codigo, descricao) values (1924, 'Entrada p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (1925, 'Retorno de mercadoria remetida p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (1926, 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação');
insert into vendas.tb_cfop (codigo, descricao) values (1931, 'Lançamento efetuado pelo tomador do serviço de transporte, quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não-inscrito na UF onde se tenha iniciado o serviço.');
insert into vendas.tb_cfop (codigo, descricao) values (1932, 'Aquisição de serviço de transporte iniciado em UF diversa daquela onde esteja inscrito o prestador');
insert into vendas.tb_cfop (codigo, descricao) values (1933, 'Aquisição de serviço tributado pelo Imposto sobre Serviços de Qualquer Natureza');
insert into vendas.tb_cfop (codigo, descricao) values (1934, 'Entrada simbólica de mercadoria recebida p/ depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (1949, 'Outra entrada de mercadoria ou prestação de serviço não especificada');
insert into vendas.tb_cfop (codigo, descricao) values (2101, 'Compra p/ industrialização ou produção rural');
insert into vendas.tb_cfop (codigo, descricao) values (2102, 'Compra p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (2111, 'Compra p/ industrialização de mercadoria recebida anteriormente em consignação industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2113, 'Compra p/ comercialização, de mercadoria recebida anteriormente em consignação mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (2116, 'Compra p/ industrialização ou produção rural originada de encomenda p/ recebimento futuro');
insert into vendas.tb_cfop (codigo, descricao) values (2117, 'Compra p/ comercialização originada de encomenda p/ recebimento futuro');
insert into vendas.tb_cfop (codigo, descricao) values (2118, 'Compra de mercadoria p/ comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem');
insert into vendas.tb_cfop (codigo, descricao) values (2120, 'Compra p/ industrialização, em venda à ordem, já recebida do vendedor remetente');
insert into vendas.tb_cfop (codigo, descricao) values (2121, 'Compra p/ comercialização, em venda à ordem, já recebida do vendedor remetente');
insert into vendas.tb_cfop (codigo, descricao) values (2122, 'Compra p/ industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (2124, 'Industrialização efetuada por outra empresa');
insert into vendas.tb_cfop (codigo, descricao) values (2125, 'Industrialização efetuada por outra empresa quando a mercadoria remetida p/ utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria');
insert into vendas.tb_cfop (codigo, descricao) values (2126, 'Compra p/ utilização na prestação de serviço sujeita ao ICMS');
insert into vendas.tb_cfop (codigo, descricao) values (2128, 'Compra p/ utilização na prestação de serviço sujeita ao ISSQN');
insert into vendas.tb_cfop (codigo, descricao) values (2151, 'Transferência p/ industrialização ou produção rural');
insert into vendas.tb_cfop (codigo, descricao) values (2152, 'Transferência p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (2153, 'Transferência de energia elétrica p/ distribuição');
insert into vendas.tb_cfop (codigo, descricao) values (2154, 'Transferência p/ utilização na prestação de serviço');
insert into vendas.tb_cfop (codigo, descricao) values (2201, 'Devolução de venda de produção do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (2202, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (2203, 'Devolução de venda de produção do estabelecimento destinada à ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (2204, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (2205, 'Anulação de valor relativo à prestação de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (2206, 'Anulação de valor relativo à prestação de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (2207, 'Anulação de valor relativo à venda de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (2208, 'Devolução de produção do estabelecimento, remetida em transferência.');
insert into vendas.tb_cfop (codigo, descricao) values (2209, 'Devolução de mercadoria adquirida ou recebida de terceiros e remetida em transferência');
insert into vendas.tb_cfop (codigo, descricao) values (2212, 'Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (2251, 'Compra de energia elétrica p/ distribuição ou comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (2252, 'Compra de energia elétrica por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2253, 'Compra de energia elétrica por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (2254, 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (2255, 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (2256, 'Compra de energia elétrica por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (2257, 'Compra de energia elétrica p/ consumo por demanda contratada');
insert into vendas.tb_cfop (codigo, descricao) values (2301, 'Aquisição de serviço de comunicação p/ execução de serviço da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (2302, 'Aquisição de serviço de comunicação por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2303, 'Aquisição de serviço de comunicação por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (2304, 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (2305, 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (2306, 'Aquisição de serviço de comunicação por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (2351, 'Aquisição de serviço de transporte p/ execução de serviço da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (2352, 'Aquisição de serviço de transporte por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2353, 'Aquisição de serviço de transporte por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (2354, 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (2355, 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (2356, 'Aquisição de serviço de transporte por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (2401, 'Compra p/ industrialização ou produção rural de mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2403, 'Compra p/ comercialização em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2406, 'Compra de bem p/ o ativo imobilizado cuja mercadoria está sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2407, 'Compra de mercadoria p/ uso ou consumo cuja mercadoria está sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2408, 'Transferência p/ industrialização ou produção rural de mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2409, 'Transferência p/ comercialização em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2410, 'Devolução de venda de produção do estabelecimento, quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2411, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2414, 'Retorno de produção do estabelecimento, remetida p/ venda fora do estabelecimento, quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2415, 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida p/ venda fora do estabelecimento em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (2501, 'Entrada de mercadoria recebida com fim específico de exportação');
insert into vendas.tb_cfop (codigo, descricao) values (2503, 'Entrada decorrente de devolução de produto industrializado pelo estabelecimento, remetido com fim específico de exportação');
insert into vendas.tb_cfop (codigo, descricao) values (2504, 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (2505, 'Entrada decorrente de devolução simbólica de mercadoria remetida p/ formação de lote de exportação, de produto industrializado ou produzido pelo próprio estabelecimento.');
insert into vendas.tb_cfop (codigo, descricao) values (2506, 'Entrada decorrente de devolução simbólica de mercadoria, adquirida ou recebida de terceiros, remetida p/ formação de lote de exportação.');
insert into vendas.tb_cfop (codigo, descricao) values (2551, 'Compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (2552, 'Transferência de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (2553, 'Devolução de venda de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (2554, 'Retorno de bem do ativo imobilizado remetido p/ uso fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (2555, 'Entrada de bem do ativo imobilizado de terceiro, remetido p/ uso no estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (2556, 'Compra de material p/ uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (2557, 'Transferência de material p/ uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (2603, 'Ressarcimento de ICMS retido por substituição tributária');
insert into vendas.tb_cfop (codigo, descricao) values (2651, 'Compra de combustível ou lubrificante p/ industrialização subseqüente');
insert into vendas.tb_cfop (codigo, descricao) values (2652, 'Compra de combustível ou lubrificante p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (2652, 'Compra de combustível ou lubrificante p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (2653, 'Compra de combustível ou lubrificante por consumidor ou usuário final');
insert into vendas.tb_cfop (codigo, descricao) values (2658, 'Transferência de combustível ou lubrificante p/ industrialização');
insert into vendas.tb_cfop (codigo, descricao) values (2659, 'Transferência de combustível ou lubrificante p/ comercialização ');
insert into vendas.tb_cfop (codigo, descricao) values (2660, 'Devolução de venda de combustível ou lubrificante destinados à industrialização subseqüente');
insert into vendas.tb_cfop (codigo, descricao) values (2661, 'Devolução de venda de combustível ou lubrificante destinados à comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (2662, 'Devolução de venda de combustível ou lubrificante destinados a consumidor ou usuário final');
insert into vendas.tb_cfop (codigo, descricao) values (2663, 'Entrada de combustível ou lubrificante p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (2664, 'Retorno de combustível ou lubrificante remetidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (2901, 'Entrada p/ industrialização por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (2902, 'Retorno de mercadoria remetida p/ industrialização por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (2903, 'Entrada de mercadoria remetida p/ industrialização e não aplicada no referido processo');
insert into vendas.tb_cfop (codigo, descricao) values (2904, 'Retorno de remessa p/ venda fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (2905, 'Entrada de mercadoria recebida p/ depósito em depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (2906, 'Retorno de mercadoria remetida p/ depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (2907, 'Retorno simbólico de mercadoria remetida p/ depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (2908, 'Entrada de bem por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (2909, 'Retorno de bem remetido por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (2910, 'Entrada de bonificação, doação ou brinde');
insert into vendas.tb_cfop (codigo, descricao) values (2911, 'Entrada de amostra grátis');
insert into vendas.tb_cfop (codigo, descricao) values (2912, 'Entrada de mercadoria ou bem recebido p/ demonstração');
insert into vendas.tb_cfop (codigo, descricao) values (2913, 'Retorno de mercadoria ou bem remetido p/ demonstração');
insert into vendas.tb_cfop (codigo, descricao) values (2914, 'Retorno de mercadoria ou bem remetido p/ exposição ou feira');
insert into vendas.tb_cfop (codigo, descricao) values (2915, 'Entrada de mercadoria ou bem recebido p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (2916, 'Retorno de mercadoria ou bem remetido p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (2917, 'Entrada de mercadoria recebida em consignação mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2918, 'Devolução de mercadoria remetida em consignação mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2919, 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (2920, 'Entrada de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (2921, 'Retorno de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (2922, 'Lançamento efetuado a título de simples faturamento decorrente de compra p/ recebimento futuro');
insert into vendas.tb_cfop (codigo, descricao) values (2923, 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem');
insert into vendas.tb_cfop (codigo, descricao) values (2924, 'Entrada p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (2925, 'Retorno de mercadoria remetida p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (2931, 'Lançamento efetuado pelo tomador do serviço de transporte, quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não-inscrito na UF onde se tenha iniciado o serviço  ');
insert into vendas.tb_cfop (codigo, descricao) values (2932, 'Aquisição de serviço de transporte iniciado em UF diversa daquela onde esteja inscrito o prestador ');
insert into vendas.tb_cfop (codigo, descricao) values (2933, 'Aquisição de serviço tributado pelo Imposto Sobre Serviços de Qualquer Natureza');
insert into vendas.tb_cfop (codigo, descricao) values (2934, 'Entrada simbólica de mercadoria recebida p/ depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (2949, 'Outra entrada de mercadoria ou prestação de serviço não especificado');
insert into vendas.tb_cfop (codigo, descricao) values (3101, 'Compra p/ industrialização ou produção rural');
insert into vendas.tb_cfop (codigo, descricao) values (3102, 'Compra p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (3126, 'Compra p/ utilização na prestação de serviço sujeita ao ICMS');
insert into vendas.tb_cfop (codigo, descricao) values (3127, 'Compra p/ industrialização sob o regime de drawback ');
insert into vendas.tb_cfop (codigo, descricao) values (3128, 'Compra p/ utilização na prestação de serviço sujeita ao ISSQN');
insert into vendas.tb_cfop (codigo, descricao) values (3129, 'Compra para industrialização sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (3201, 'Devolução de venda de produção do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (3202, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (3205, 'Anulação de valor relativo à prestação de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (3206, 'Anulação de valor relativo à prestação de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (3207, 'Anulação de valor relativo à venda de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (3211, 'Devolução de venda de produção do estabelecimento sob o regime de drawback ');
insert into vendas.tb_cfop (codigo, descricao) values (3212, 'Devolução de venda no mercado externo de mercadoria industrializada sob o Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (3251, 'Compra de energia elétrica p/ distribuição ou comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (3301, 'Aquisição de serviço de comunicação p/ execução de serviço da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (3351, 'Aquisição de serviço de transporte p/ execução de serviço da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (3352, 'Aquisição de serviço de transporte por estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (3353, 'Aquisição de serviço de transporte por estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (3354, 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (3355, 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (3356, 'Aquisição de serviço de transporte por estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (3503, 'Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação');
insert into vendas.tb_cfop (codigo, descricao) values (3551, 'Compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (3553, 'Devolução de venda de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (3556, 'Compra de material p/ uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (3651, 'Compra de combustível ou lubrificante p/ industrialização subseqüente');
insert into vendas.tb_cfop (codigo, descricao) values (3652, 'Compra de combustível ou lubrificante p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (3653, 'Compra de combustível ou lubrificante por consumidor ou usuário final');
insert into vendas.tb_cfop (codigo, descricao) values (3930, 'Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária');
insert into vendas.tb_cfop (codigo, descricao) values (3949, 'Outra entrada de mercadoria ou prestação de serviço não especificado');
insert into vendas.tb_cfop (codigo, descricao) values (5101, 'Venda de produção do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5102, 'Venda de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (5103, 'Venda de produção do estabelecimento efetuada fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5104, 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5105, 'Venda de produção do estabelecimento que não deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (5106, 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar ');
insert into vendas.tb_cfop (codigo, descricao) values (5109, 'Venda de produção do estabelecimento destinada à ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (5110, 'Venda de mercadoria, adquirida ou recebida de terceiros, destinada à ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (5111, 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5112, 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5113, 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (5114, 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (5115, 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (5116, 'Venda de produção do estabelecimento originada de encomenda p/ entrega futura');
insert into vendas.tb_cfop (codigo, descricao) values (5117, 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda p/ entrega futura');
insert into vendas.tb_cfop (codigo, descricao) values (5118, 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem');
insert into vendas.tb_cfop (codigo, descricao) values (5119, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem');
insert into vendas.tb_cfop (codigo, descricao) values (5120, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem');
insert into vendas.tb_cfop (codigo, descricao) values (5122, 'Venda de produção do estabelecimento remetida p/ industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (5123, 'Venda de mercadoria adquirida ou recebida de terceiros remetida p/ industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (5124, 'Industrialização efetuada p/ outra empresa');
insert into vendas.tb_cfop (codigo, descricao) values (5125, 'Industrialização efetuada p/ outra empresa quando a mercadoria recebida p/ utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria');
insert into vendas.tb_cfop (codigo, descricao) values (5129, 'Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (5151, 'Transferência de produção do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5152, 'Transferência de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (5153, 'Transferência de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (5155, 'Transferência de produção do estabelecimento, que não deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (5156, 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (5201, 'Devolução de compra p/ industrialização ou produção rural');
insert into vendas.tb_cfop (codigo, descricao) values (5202, 'Devolução de compra p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (5205, 'Anulação de valor relativo a aquisição de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (5206, 'Anulação de valor relativo a aquisição de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (5207, 'Anulação de valor relativo à compra de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (5208, 'Devolução de mercadoria recebida em transferência p/ industrialização ou produção rural ');
insert into vendas.tb_cfop (codigo, descricao) values (5209, 'Devolução de mercadoria recebida em transferência p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (5210, 'Devolução de compra p/ utilização na prestação de serviço');
insert into vendas.tb_cfop (codigo, descricao) values (5251, 'Venda de energia elétrica p/ distribuição ou comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (5252, 'Venda de energia elétrica p/ estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5253, 'Venda de energia elétrica p/ estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (5254, 'Venda de energia elétrica p/ estabelecimento prestador de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (5255, 'Venda de energia elétrica p/ estabelecimento prestador de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (5256, 'Venda de energia elétrica p/ estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (5257, 'Venda de energia elétrica p/ consumo por demanda contratada');
insert into vendas.tb_cfop (codigo, descricao) values (5258, 'Venda de energia elétrica a não contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (5301, 'Prestação de serviço de comunicação p/ execução de serviço da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (5302, 'Prestação de serviço de comunicação a estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5303, 'Prestação de serviço de comunicação a estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (5304, 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (5305, 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (5306, 'Prestação de serviço de comunicação a estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (5307, 'Prestação de serviço de comunicação a não contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (5351, 'Prestação de serviço de transporte p/ execução de serviço da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (5352, 'Prestação de serviço de transporte a estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5353, 'Prestação de serviço de transporte a estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (5354, 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (5355, 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (5356, 'Prestação de serviço de transporte a estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (5357, 'Prestação de serviço de transporte a não contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (5359, 'Prestação de serviço de transporte a contribuinte ou a não-contribuinte, quando a mercadoria transportada esteja dispensada de emissão de Nota Fiscal  ');
insert into vendas.tb_cfop (codigo, descricao) values (5360, 'Prestação de serviço de transporte a contribuinte-substituto em relação ao serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (5401, 'Venda de produção do estabelecimento quando o produto esteja sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5402, 'Venda de produção do estabelecimento de produto sujeito a ST, em operação entre contribuintes substitutos do mesmo produto');
insert into vendas.tb_cfop (codigo, descricao) values (5403, 'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita a ST, na condição de contribuinte-substituto');
insert into vendas.tb_cfop (codigo, descricao) values (5405, 'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita a ST, na condição de contribuinte-substituído');
insert into vendas.tb_cfop (codigo, descricao) values (5408, 'Transferência de produção do estabelecimento quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5409, 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5410, 'Devolução de compra p/ industrialização de mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5411, 'Devolução de compra p/ comercialização em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5412, 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5413, 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita a ST.');
insert into vendas.tb_cfop (codigo, descricao) values (5414, 'Remessa de produção do estabelecimento p/ venda fora do estabelecimento, quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5415, 'Remessa de mercadoria adquirida ou recebida de terceiros p/ venda fora do estabelecimento, em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (5451, 'Remessa de animal e de insumo p/ estabelecimento produtor');
insert into vendas.tb_cfop (codigo, descricao) values (5501, 'Remessa de produção do estabelecimento, com fim específico de exportação');
insert into vendas.tb_cfop (codigo, descricao) values (5502, 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação');
insert into vendas.tb_cfop (codigo, descricao) values (5503, 'Devolução de mercadoria recebida com fim específico de exportação');
insert into vendas.tb_cfop (codigo, descricao) values (5504, 'Remessa de mercadoria p/ formação de lote de exportação, de produto industrializado ou produzido pelo próprio estabelecimento.');
insert into vendas.tb_cfop (codigo, descricao) values (5505, 'Remessa de mercadoria, adquirida ou recebida de terceiros, p/ formação de lote de exportação.');
insert into vendas.tb_cfop (codigo, descricao) values (5551, 'Venda de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (5552, 'Transferência de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (5553, 'Devolução de compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (5554, 'Remessa de bem do ativo imobilizado p/ uso fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5555, 'Devolução de bem do ativo imobilizado de terceiro, recebido p/ uso no estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5556, 'Devolução de compra de material de uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (5557, 'Transferência de material de uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (5601, 'Transferência de crédito de ICMS acumulado');
insert into vendas.tb_cfop (codigo, descricao) values (5602, 'Transferência de saldo credor do ICMS, p/ outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor do ICMS');
insert into vendas.tb_cfop (codigo, descricao) values (5603, 'Ressarcimento de ICMS retido por substituição tributária');
insert into vendas.tb_cfop (codigo, descricao) values (5605, 'Transferência de saldo devedor do ICMS de outro estabelecimento da mesma empresa  ');
insert into vendas.tb_cfop (codigo, descricao) values (5606, 'Utilização de saldo credor do ICMS p/ extinção por compensação de débitos fiscais');
insert into vendas.tb_cfop (codigo, descricao) values (5651, 'Venda de combustível ou lubrificante de produção do estabelecimento destinados à industrialização subseqüente');
insert into vendas.tb_cfop (codigo, descricao) values (5652, 'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados à comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (5653, 'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados a consumidor ou usuário final');
insert into vendas.tb_cfop (codigo, descricao) values (5654, 'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à industrialização subseqüente');
insert into vendas.tb_cfop (codigo, descricao) values (5655, 'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (5656, 'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados a consumidor ou usuário final');
insert into vendas.tb_cfop (codigo, descricao) values (5657, 'Remessa de combustível ou lubrificante, adquiridos ou recebidos de terceiros, p/ venda fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5658, 'Transferência de combustível ou lubrificante de produção do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5659, 'Transferência de combustível ou lubrificante adquiridos ou recebidos de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (5660, 'Devolução de compra de combustível ou lubrificante adquiridos p/ industrialização subseqüente');
insert into vendas.tb_cfop (codigo, descricao) values (5661, 'Devolução de compra de combustível ou lubrificante adquiridos p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (5662, 'Devolução de compra de combustível ou lubrificante adquiridos por consumidor ou usuário final');
insert into vendas.tb_cfop (codigo, descricao) values (5663, 'Remessa p/ armazenagem de combustível ou lubrificante');
insert into vendas.tb_cfop (codigo, descricao) values (5664, 'Retorno de combustível ou lubrificante recebidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (5665, 'Retorno simbólico de combustível ou lubrificante recebidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (5666, 'Remessa, por conta e ordem de terceiros, de combustível ou lubrificante recebidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (5667, 'Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra UF');
insert into vendas.tb_cfop (codigo, descricao) values (5901, 'Remessa p/ industrialização por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (5902, 'Retorno de mercadoria utilizada na industrialização por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (5903, 'Retorno de mercadoria recebida p/ industrialização e não aplicada no referido processo');
insert into vendas.tb_cfop (codigo, descricao) values (5904, 'Remessa p/ venda fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (5905, 'Remessa p/ depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (5906, 'Retorno de mercadoria depositada em depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (5907, 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (5908, 'Remessa de bem por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (5909, 'Retorno de bem recebido por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (5910, 'Remessa em bonificação, doação ou brinde');
insert into vendas.tb_cfop (codigo, descricao) values (5911, 'Remessa de amostra grátis');
insert into vendas.tb_cfop (codigo, descricao) values (5912, 'Remessa de mercadoria ou bem p/ demonstração');
insert into vendas.tb_cfop (codigo, descricao) values (5913, 'Retorno de mercadoria ou bem recebido p/ demonstração');
insert into vendas.tb_cfop (codigo, descricao) values (5914, 'Remessa de mercadoria ou bem p/ exposição ou feira');
insert into vendas.tb_cfop (codigo, descricao) values (5915, 'Remessa de mercadoria ou bem p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (5916, 'Retorno de mercadoria ou bem recebido p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (5917, 'Remessa de mercadoria em consignação mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5918, 'Devolução de mercadoria recebida em consignação mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5919, 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (5920, 'Remessa de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (5921, 'Devolução de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (5922, 'Lançamento efetuado a título de simples faturamento decorrente de venda p/ entrega futura');
insert into vendas.tb_cfop (codigo, descricao) values (5923, 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado.');
insert into vendas.tb_cfop (codigo, descricao) values (5924, 'Remessa p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (5925, 'Retorno de mercadoria recebida p/ industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (5926, 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação');
insert into vendas.tb_cfop (codigo, descricao) values (5927, 'Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração');
insert into vendas.tb_cfop (codigo, descricao) values (5928, 'Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa');
insert into vendas.tb_cfop (codigo, descricao) values (5929, 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF');
insert into vendas.tb_cfop (codigo, descricao) values (5931, 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na UF onde iniciado o serviço');
insert into vendas.tb_cfop (codigo, descricao) values (5932, 'Prestação de serviço de transporte iniciada em UF diversa daquela onde inscrito o prestador');
insert into vendas.tb_cfop (codigo, descricao) values (5933, 'Prestação de serviço tributado pelo Imposto Sobre Serviços de Qualquer Natureza');
insert into vendas.tb_cfop (codigo, descricao) values (5934, 'Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado.');
insert into vendas.tb_cfop (codigo, descricao) values (5949, 'Outra saída de mercadoria ou prestação de serviço não especificado');
insert into vendas.tb_cfop (codigo, descricao) values (6101, 'Venda de produção do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6102, 'Venda de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (6103, 'Venda de produção do estabelecimento, efetuada fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6104, 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6105, 'Venda de produção do estabelecimento que não deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (6106, 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (6107, 'Venda de produção do estabelecimento, destinada a não contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (6108, 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (6109, 'Venda de produção do estabelecimento destinada à ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (6110, 'Venda de mercadoria, adquirida ou recebida de terceiros, destinada à ZFM ou ALC');
insert into vendas.tb_cfop (codigo, descricao) values (6111, 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6112, 'Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6113, 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (6114, 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (6115, 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil');
insert into vendas.tb_cfop (codigo, descricao) values (6116, 'Venda de produção do estabelecimento originada de encomenda p/ entrega futura');
insert into vendas.tb_cfop (codigo, descricao) values (6117, 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda p/ entrega futura');
insert into vendas.tb_cfop (codigo, descricao) values (6118, 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem');
insert into vendas.tb_cfop (codigo, descricao) values (6119, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem');
insert into vendas.tb_cfop (codigo, descricao) values (6120, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem');
insert into vendas.tb_cfop (codigo, descricao) values (6122, 'Venda de produção do estabelecimento remetida p/ industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (6123, 'Venda de mercadoria adquirida ou recebida de terceiros remetida p/ industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (6124, 'Industrialização efetuada p/ outra empresa');
insert into vendas.tb_cfop (codigo, descricao) values (6125, 'Industrialização efetuada p/ outra empresa quando a mercadoria recebida p/ utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria');
insert into vendas.tb_cfop (codigo, descricao) values (6129, 'Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (6151, 'Transferência de produção do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6152, 'Transferência de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (6153, 'Transferência de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (6155, 'Transferência de produção do estabelecimento, que não deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (6156, 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (6201, 'Devolução de compra p/ industrialização ou produção rural');
insert into vendas.tb_cfop (codigo, descricao) values (6202, 'Devolução de compra p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (6205, 'Anulação de valor relativo a aquisição de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (6206, 'Anulação de valor relativo a aquisição de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (6207, 'Anulação de valor relativo à compra de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (6208, 'Devolução de mercadoria recebida em transferência p/ industrialização ou produção rural ');
insert into vendas.tb_cfop (codigo, descricao) values (6209, 'Devolução de mercadoria recebida em transferência p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (6210, 'Devolução de compra p/ utilização na prestação de serviço');
insert into vendas.tb_cfop (codigo, descricao) values (6251, 'Venda de energia elétrica p/ distribuição ou comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (6252, 'Venda de energia elétrica p/ estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6253, 'Venda de energia elétrica p/ estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (6254, 'Venda de energia elétrica p/ estabelecimento prestador de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (6255, 'Venda de energia elétrica p/ estabelecimento prestador de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (6256, 'Venda de energia elétrica p/ estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (6257, 'Venda de energia elétrica p/ consumo por demanda contratada');
insert into vendas.tb_cfop (codigo, descricao) values (6258, 'Venda de energia elétrica a não contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (6301, 'Prestação de serviço de comunicação p/ execução de serviço da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (6302, 'Prestação de serviço de comunicação a estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6303, 'Prestação de serviço de comunicação a estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (6304, 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (6305, 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (6306, 'Prestação de serviço de comunicação a estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (6307, 'Prestação de serviço de comunicação a não contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (6351, 'Prestação de serviço de transporte p/ execução de serviço da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (6352, 'Prestação de serviço de transporte a estabelecimento industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6353, 'Prestação de serviço de transporte a estabelecimento comercial');
insert into vendas.tb_cfop (codigo, descricao) values (6354, 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (6355, 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (6356, 'Prestação de serviço de transporte a estabelecimento de produtor rural');
insert into vendas.tb_cfop (codigo, descricao) values (6357, 'Prestação de serviço de transporte a não contribuinte');
insert into vendas.tb_cfop (codigo, descricao) values (6359, 'Prestação de serviço de transporte a contribuinte ou a não-contribuinte, quando a mercadoria transportada esteja dispensada de emissão de Nota Fiscal  ');
insert into vendas.tb_cfop (codigo, descricao) values (6360, 'Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte  ');
insert into vendas.tb_cfop (codigo, descricao) values (6401, 'Venda de produção do estabelecimento quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6402, 'Venda de produção do estabelecimento de produto sujeito a ST, em operação entre contribuintes substitutos do mesmo produto');
insert into vendas.tb_cfop (codigo, descricao) values (6403, 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita a ST, na condição de contribuinte substituto');
insert into vendas.tb_cfop (codigo, descricao) values (6404, 'Venda de mercadoria sujeita a ST, cujo imposto já tenha sido retido anteriormente');
insert into vendas.tb_cfop (codigo, descricao) values (6408, 'Transferência de produção do estabelecimento quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6409, 'Transferência de mercadoria adquirida ou recebida de terceiros, sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6410, 'Devolução de compra p/ industrialização ou ptrodução rural quando a mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6411, 'Devolução de compra p/ comercialização em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6412, 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6413, 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6414, 'Remessa de produção do estabelecimento p/ venda fora do estabelecimento, quando o produto sujeito a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6415, 'Remessa de mercadoria adquirida ou recebida de terceiros p/ venda fora do estabelecimento, quando a referida ração com mercadoria sujeita a ST');
insert into vendas.tb_cfop (codigo, descricao) values (6501, 'Remessa de produção do estabelecimento, com fim específico de exportação');
insert into vendas.tb_cfop (codigo, descricao) values (6502, 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação');
insert into vendas.tb_cfop (codigo, descricao) values (6503, 'Devolução de mercadoria recebida com fim específico de exportação');
insert into vendas.tb_cfop (codigo, descricao) values (6504, 'Remessa de mercadoria p/ formação de lote de exportação, de produto industrializado ou produzido pelo próprio estabelecimento.');
insert into vendas.tb_cfop (codigo, descricao) values (6505, 'Remessa de mercadoria, adquirida ou recebida de terceiros, p/ formação de lote de exportação.');
insert into vendas.tb_cfop (codigo, descricao) values (6551, 'Venda de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (6552, 'Transferência de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (6553, 'Devolução de compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (6554, 'Remessa de bem do ativo imobilizado p/ uso fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6555, 'Devolução de bem do ativo imobilizado de terceiro, recebido p/ uso no estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6556, 'Devolução de compra de material de uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (6557, 'Transferência de material de uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (6603, 'Ressarcimento de ICMS retido por substituição tributária');
insert into vendas.tb_cfop (codigo, descricao) values (6651, 'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados à industrialização subseqüente');
insert into vendas.tb_cfop (codigo, descricao) values (6652, 'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados à comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (6653, 'Venda de combustível ou lubrificante, de produção do estabelecimento, destinados a consumidor ou usuário final');
insert into vendas.tb_cfop (codigo, descricao) values (6654, 'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à industrialização subseqüente');
insert into vendas.tb_cfop (codigo, descricao) values (6655, 'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados à comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (6656, 'Venda de combustível ou lubrificante, adquiridos ou recebidos de terceiros, destinados a consumidor ou usuário final');
insert into vendas.tb_cfop (codigo, descricao) values (6657, 'Remessa de combustível ou lubrificante, adquiridos ou recebidos de terceiros, p/ venda fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6658, 'Transferência de combustível ou lubrificante de produção do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6659, 'Transferência de combustível ou lubrificante adquiridos ou recebidos de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (6660, 'Devolução de compra de combustível ou lubrificante adquiridos p/ industrialização subseqüente');
insert into vendas.tb_cfop (codigo, descricao) values (6661, 'Devolução de compra de combustível ou lubrificante adquiridos p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (6662, 'Devolução de compra de combustível ou lubrificante adquiridos por consumidor ou usuário final');
insert into vendas.tb_cfop (codigo, descricao) values (6663, 'Remessa p/ armazenagem de combustível ou lubrificante');
insert into vendas.tb_cfop (codigo, descricao) values (6664, 'Retorno de combustível ou lubrificante recebidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (6665, 'Retorno simbólico de combustível ou lubrificante recebidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (6666, 'Remessa, por conta e ordem de terceiros, de combustível ou lubrificante recebidos p/ armazenagem');
insert into vendas.tb_cfop (codigo, descricao) values (6667, 'Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra UF diferente da que ocorrer o consumo');
insert into vendas.tb_cfop (codigo, descricao) values (6901, 'Remessa p/ industrialização por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (6902, 'Retorno de mercadoria utilizada na industrialização por encomenda');
insert into vendas.tb_cfop (codigo, descricao) values (6903, 'Retorno de mercadoria recebida p/ industrialização e não aplicada no referido processo');
insert into vendas.tb_cfop (codigo, descricao) values (6904, 'Remessa p/ venda fora do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (6905, 'Remessa p/ depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (6906, 'Retorno de mercadoria depositada em depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (6907, 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral');
insert into vendas.tb_cfop (codigo, descricao) values (6908, 'Remessa de bem por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (6909, 'Retorno de bem recebido por conta de contrato de comodato');
insert into vendas.tb_cfop (codigo, descricao) values (6910, 'Remessa em bonificação, doação ou brinde');
insert into vendas.tb_cfop (codigo, descricao) values (6911, 'Remessa de amostra grátis');
insert into vendas.tb_cfop (codigo, descricao) values (6912, 'Remessa de mercadoria ou bem p/ demonstração');
insert into vendas.tb_cfop (codigo, descricao) values (6913, 'Retorno de mercadoria ou bem recebido p/ demonstração');
insert into vendas.tb_cfop (codigo, descricao) values (6914, 'Remessa de mercadoria ou bem p/ exposição ou feira');
insert into vendas.tb_cfop (codigo, descricao) values (6915, 'Remessa de mercadoria ou bem p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (6916, 'Retorno de mercadoria ou bem recebido p/ conserto ou reparo');
insert into vendas.tb_cfop (codigo, descricao) values (6917, 'Remessa de mercadoria em consignação mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6918, 'Devolução de mercadoria recebida em consignação mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6919, 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial');
insert into vendas.tb_cfop (codigo, descricao) values (6920, 'Remessa de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (6921, 'Devolução de vasilhame ou sacaria');
insert into vendas.tb_cfop (codigo, descricao) values (6922, 'Lançamento efetuado a título de simples faturamento decorrente de venda p/ entrega futura');
insert into vendas.tb_cfop (codigo, descricao) values (6923, 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado');
insert into vendas.tb_cfop (codigo, descricao) values (6924, 'Remessa p/ industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (6925, 'Retorno de mercadoria recebida p/ industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente');
insert into vendas.tb_cfop (codigo, descricao) values (6929, 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF');
insert into vendas.tb_cfop (codigo, descricao) values (6931, 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na UF onde iniciado o serviço');
insert into vendas.tb_cfop (codigo, descricao) values (6932, 'Prestação de serviço de transporte iniciada em UF diversa daquela onde inscrito o prestador');
insert into vendas.tb_cfop (codigo, descricao) values (6933, 'Prestação de serviço tributado pelo Imposto Sobre Serviços de Qualquer Natureza ');
insert into vendas.tb_cfop (codigo, descricao) values (6934, 'Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado');
insert into vendas.tb_cfop (codigo, descricao) values (6949, 'Outra saída de mercadoria ou prestação de serviço não especificado');
insert into vendas.tb_cfop (codigo, descricao) values (7101, 'Venda de produção do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (7102, 'Venda de mercadoria adquirida ou recebida de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (7105, 'Venda de produção do estabelecimento, que não deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (7106, 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
insert into vendas.tb_cfop (codigo, descricao) values (7127, 'Venda de produção do estabelecimento sob o regime de drawback ');
insert into vendas.tb_cfop (codigo, descricao) values (7129, 'Venda de produção do estabelecimento ao mercado externo de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (7201, 'Devolução de compra p/ industrialização ou produção rural');
insert into vendas.tb_cfop (codigo, descricao) values (7202, 'Devolução de compra p/ comercialização');
insert into vendas.tb_cfop (codigo, descricao) values (7205, 'Anulação de valor relativo à aquisição de serviço de comunicação');
insert into vendas.tb_cfop (codigo, descricao) values (7206, 'Anulação de valor relativo a aquisição de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (7207, 'Anulação de valor relativo à compra de energia elétrica');
insert into vendas.tb_cfop (codigo, descricao) values (7210, 'Devolução de compra p/ utilização na prestação de serviço');
insert into vendas.tb_cfop (codigo, descricao) values (7211, 'Devolução de compras p/ industrialização sob o regime de drawback ');
insert into vendas.tb_cfop (codigo, descricao) values (7212, 'Devolução de compras para industrialização sob o regime de Regime Aduaneiro Especial de Entreposto Industrial (Recof-Sped)');
insert into vendas.tb_cfop (codigo, descricao) values (7251, 'Venda de energia elétrica p/ o exterior');
insert into vendas.tb_cfop (codigo, descricao) values (7301, 'Prestação de serviço de comunicação p/ execução de serviço da mesma natureza');
insert into vendas.tb_cfop (codigo, descricao) values (7358, 'Prestação de serviço de transporte');
insert into vendas.tb_cfop (codigo, descricao) values (7501, 'Exportação de mercadorias recebidas com fim específico de exportação');
insert into vendas.tb_cfop (codigo, descricao) values (7551, 'Venda de bem do ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (7553, 'Devolução de compra de bem p/ o ativo imobilizado');
insert into vendas.tb_cfop (codigo, descricao) values (7556, 'Devolução de compra de material de uso ou consumo');
insert into vendas.tb_cfop (codigo, descricao) values (7651, 'Venda de combustível ou lubrificante de produção do estabelecimento');
insert into vendas.tb_cfop (codigo, descricao) values (7654, 'Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros');
insert into vendas.tb_cfop (codigo, descricao) values (7667, 'Venda de combustível ou lubrificante a consumidor ou usuário final');
insert into vendas.tb_cfop (codigo, descricao) values (7930, 'Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária');
insert into vendas.tb_cfop (codigo, descricao) values (7949, 'Outra saída de mercadoria ou prestação de serviço não especificado');
